server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:///seat?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/modules/



mybatis:
  mapper-locations: classpath:/mapper/*/*.xml

logging:
  level:
    com.chen: debug