server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql:///seat?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/modules/
  aop:
    proxy-target-class: false
  main:
    banner-mode: OFF
  task:
    execution:
      pool:
        core-size: 3
        max-size: 256
        keep-alive: 60000
        queue-capacity: 256
      thread-name-prefix: seat-service-task-
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml

logging:
  level:
    com.chen: debug
shiro:
  loginUrl: /login.html
